.TH 4HEAD 1 
.SH NAME
meta-document for 4head core utilities.
you should read this, these utilities differ from traditional coreutils.
.SH COMMANDS

.B
succ [int]
\- return a given exit code, or 0

.B
repeat <string>
\- print a given string until stopped

.B
ls <directory>
\- print all files in a directory

.B
cat <file>
\- print contents of ONE text file

.B
pwd
\- print working directory
